[package]
name = "solana-sandbox-counter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_sandbox_counter"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "~1.18.26"
thiserror = "1.0.64"

[package.metadata.audit]
ignore = [
  "RUSTSEC-2023-0071",
  "RUSTSEC-2023-0031",
  "RUSTSEC-2020-0071",
  "RUSTSEC-2024-0370",
  "RUSTSEC-2024-0019",
  "RUSTSEC-2020-0159",
  "RUSTSEC-2021-0145",
  "RUSTSEC-2022-0090",
  "RUSTSEC-2024-0437"
]
