[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../../crates/config" }
errors = { path = "../../crates/errors" }
observability = { path = "../../crates/observability" }
shared = { path = "../../crates/shared" }

argon2 = "LTS Estável"
rand = "Versão mais recente"

jsonwebtoken = "Versão mais recente"

serde = { version = "1", features = ["derive"] }

uuid = { version = "1", features = ["v4"] }

chrono = { version = ">= 0.4.38", features = ["serde"] }

axum = "LTS Estável"
tokio = { version = "Versão mais recente", features = ["full"] }
tower = "LTS Estável"
