[advisories]
ignore = [
  "RUSTSEC-2023-0071",
  "RUSTSEC-2023-0031",
  "RUSTSEC-2020-0071",
  "RUSTSEC-2024-0370",
  "RUSTSEC-2024-0019",
  "RUSTSEC-2020-0159",
  "RUSTSEC-2021-0145",
  "RUSTSEC-2022-0090",
  "RUSTSEC-2024-0437"
]
informational_warnings = ["unmaintained", "notice"]
severity_threshold = "critical"

[output]
deny = []
