[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = ">= 0.4.38", features = ["serde"] }

# Precisão decimal para valores monetários
rust_decimal = { version = "1", features = ["serde"] }
